# Generated by Django 3.2.4 on 2022-02-08 03:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtdatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('region', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RTデータ',
                'db_table': 'rtdata',
            },
        ),
        migrations.CreateModel(
            name='Ctdatas',
            fields=[
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('ctdata', models.FileField(upload_to='ctdata/')),
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
            ],
            options={
                'verbose_name_plural': 'CTデータ',
                'db_table': 'ctdatas',
            },
        ),
        migrations.CreateModel(
            name='Plandatas',
            fields=[
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('plandata', models.FileField(upload_to='plandata/')),
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
            ],
            options={
                'verbose_name_plural': 'プランデータ',
                'db_table': 'plandatas',
            },
        ),
        migrations.CreateModel(
            name='Stracturedatas',
            fields=[
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('stracturedata', models.FileField(upload_to='stracturedata/')),
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
            ],
            options={
                'verbose_name_plural': 'ストラクチャデータ',
                'db_table': 'stracturedatas',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 3, 27, 25, 239636, tzinfo=utc))),
                ('title', models.CharField(max_length=100, null=True)),
                ('memo', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memo',
            },
        ),
    ]
