# Generated by Django 3.2.4 on 2022-02-06 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtdatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RTデータ',
                'db_table': 'rtdata',
            },
        ),
        migrations.CreateModel(
            name='Ctdatas',
            fields=[
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'CTデータ',
                'db_table': 'ctdatas',
            },
        ),
        migrations.CreateModel(
            name='Plandatas',
            fields=[
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'プランデータ',
                'db_table': 'plandata',
            },
        ),
        migrations.CreateModel(
            name='Stracturedatas',
            fields=[
                ('rtdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.rtdatas')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'ストラクチャデータ',
                'db_table': 'stracturedatas',
            },
        ),
    ]
