# Generated by Django 3.2.4 on 2022-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='ctdatas',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ctdatas',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plandatas',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plandatas',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rtdatas',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rtdatas',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stracturedatas',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stracturedatas',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
