# Generated by Django 3.2.4 on 2022-02-06 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20220207_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdatas',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ctdatas',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memo',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plandatas',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plandatas',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rtdatas',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rtdatas',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stracturedatas',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stracturedatas',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 23, 0, 3, 334074, tzinfo=utc)),
        ),
    ]
