# Generated by Django 3.2.4 on 2022-02-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220206_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
