# Generated by Django 3.2.4 on 2022-02-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='memo',
        ),
    ]
