# Generated by Django 3.2.4 on 2022-02-03 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rtapp', '0002_add_person_scholl_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 22, 19, 18, 169437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 22, 19, 18, 169437, tzinfo=utc)),
        ),
    ]
