# Generated by Django 3.2.4 on 2022-02-05 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rtapp', '0005_auto_20220204_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 5, 48, 57, 659762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 5, 48, 57, 659762, tzinfo=utc)),
        ),
    ]
